### What is Numpy

Numpy stands for numerical python, it is basically used for number computation and scientific calc etc. We can use the numpy with pandas and with other python package as well.

Note: Fundamental package for array computing in Python

Array: Array is the collection of similar data type, where as in the list we can store any kind of data such as : int, float, str, bool etc

$Q$. is it possible to store number and string in the array collection?   
$A$. No

In [1]:
import numpy as np

In [3]:
lstOfNumber = [10,20,30,40,50,100]

In [4]:
lstOfNumber

[10, 20, 30, 40, 50, 100]

In [5]:
arr = np.array(lstOfNumber)

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr

array([ 10,  20,  30,  40,  50, 100])

In [8]:
print(arr)

[ 10  20  30  40  50 100]


In [10]:
np.array([10,14,False,56,100,True])

array([ 10,  14,   0,  56, 100,   1])

In [11]:
np.array([10,"A",14,False,56,100,True])

array(['10', 'A', '14', 'False', '56', '100', 'True'], dtype='<U11')

In [12]:
np.array([10,12,45.89])

array([10.  , 12.  , 45.89])

In [13]:
lstOfNumber

[10, 20, 30, 40, 50, 100]

In [14]:
[i + 5 for i in lstOfNumber]

[15, 25, 35, 45, 55, 105]

In [15]:
arr

array([ 10,  20,  30,  40,  50, 100])

In [16]:
arr + 5

array([ 15,  25,  35,  45,  55, 105])

In [17]:
arr - 5

array([ 5, 15, 25, 35, 45, 95])

In [18]:
arr * 2

array([ 20,  40,  60,  80, 100, 200])

In [19]:
arr ** 2

array([  100,   400,   900,  1600,  2500, 10000])

### Python numPy aRange Function

In [20]:
arr = np.arange(10)

In [21]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [23]:
arr = np.arange(10,100,2)

In [24]:
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [25]:
arr = np.arange(100,-5,-10)

In [26]:
arr

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10,   0])

In [27]:
lst = list(range(5,10000000))

In [28]:
len(lst)

9999995

In [30]:
%%time
for _ in range(20):
    test = [x ** 2 for x in lst]

CPU times: total: 36.3 s
Wall time: 41.4 s


In [31]:
%%time
array_lst = np.array(lst)
for _ in range(20):
    test = array_lst ** 2

CPU times: total: 1.34 s
Wall time: 1.39 s


### Random Number using Python Numpy

In [32]:
import random

In [36]:
random.randint(10,100)

31

In [54]:
arr = np.random.randint(low = 10, high = 100, size = 100, dtype=int)

In [55]:
arr

array([42, 11, 13, 46, 13, 72, 33, 60, 98, 45, 25, 12, 64, 35, 66, 33, 44,
       81, 29, 94, 76, 88, 97, 76, 96, 97, 52, 36, 98, 44, 89, 78, 69, 67,
       53, 16, 27, 41, 17, 66, 97, 38, 78, 12, 87, 68, 66, 65, 12, 31, 68,
       34, 17, 98, 57, 76, 89, 60, 71, 19, 97, 54, 12, 29, 69, 95, 28, 49,
       49, 32, 98, 11, 93, 25, 72, 83, 53, 72, 94, 58, 79, 52, 46, 11, 81,
       77, 60, 27, 91, 93, 34, 39, 83, 88, 19, 60, 60, 20, 92, 16])

In [42]:
arr1 = np.random.randint(low = 10, high = 100, size = 50)

In [43]:
arr1

array([56, 71, 77, 19, 91, 20, 33, 20, 96, 22, 82, 51, 67, 80, 67, 37, 72,
       12, 13, 63, 82, 71, 11, 94, 22, 85, 21, 96, 79, 23, 75, 31, 61, 66,
       23, 21, 50, 32, 37, 85, 59, 74, 34, 36, 81, 68, 63, 28, 51, 19])

In [53]:
np.random.rand()

0.7233173598237962

In [60]:
np.array(arr1, dtype = 'float')

array([56., 71., 77., 19., 91., 20., 33., 20., 96., 22., 82., 51., 67.,
       80., 67., 37., 72., 12., 13., 63., 82., 71., 11., 94., 22., 85.,
       21., 96., 79., 23., 75., 31., 61., 66., 23., 21., 50., 32., 37.,
       85., 59., 74., 34., 36., 81., 68., 63., 28., 51., 19.])

In [61]:
arr1 = np.array([23,45,67,23,56,78,90,78])
arr2 = np.array([11,45,98,56,45,24,89,49,23])

In [62]:
np.intersect1d(arr1,arr2)

array([23, 45, 56])

In [63]:
np.setdiff1d(arr1,arr2)

array([67, 78, 90])

In [64]:
np.setdiff1d(arr2,arr1)

array([11, 24, 49, 89, 98])

In [65]:
# addition of arrays

In [66]:
arr1 + arr2

ValueError: operands could not be broadcast together with shapes (8,) (9,) 

In [69]:
print("Array-1: ",len(arr1),"Array-2: ", len(arr2))

Array-1:  8 Array-2:  9


In [70]:
# how to add an item into the array

In [72]:
arr1 = np.append(arr1,10)

In [73]:
len(arr1)

9

In [74]:
arr1

array([23, 45, 67, 23, 56, 78, 90, 78, 10])

In [75]:
# can you add 99 on the first index

In [77]:
arr1 = np.insert(arr1,1,99)

In [78]:
arr1

array([23, 99, 45, 67, 23, 56, 78, 90, 78, 10])

In [79]:
len(arr1)

10

In [80]:
len(arr2)

9

In [81]:
arr2 = np.append(arr2,45)

In [82]:
print("Array-1: ",len(arr1),"Array-2: ", len(arr2))

Array-1:  10 Array-2:  10


In [83]:
arr1

array([23, 99, 45, 67, 23, 56, 78, 90, 78, 10])

In [84]:
arr2

array([11, 45, 98, 56, 45, 24, 89, 49, 23, 45])

### How to delete a specific item from the array

In [85]:
arr1 = np.delete(arr1,3)

In [86]:
arr1

array([23, 99, 45, 23, 56, 78, 90, 78, 10])

In [87]:
arr2 = np.delete(arr2,-3)

In [88]:
arr2

array([11, 45, 98, 56, 45, 24, 89, 23, 45])

In [91]:
np.append(arr2,1000)

array([  11,   45,   98,   56,   45,   24,   89,   23,   45, 1000])

In [92]:
arr2

array([11, 45, 98, 56, 45, 24, 89, 23, 45])

### Key Note:

NumPy arrays are immutable in size, operations like append, insert or delete
create a new array and do no modify the original array.

In [94]:
print(arr1)
print(arr2)

[23 99 45 23 56 78 90 78 10]
[11 45 98 56 45 24 89 23 45]


In [93]:
arr1 + arr2

array([ 34, 144, 143,  79, 101, 102, 179, 101,  55])

In [95]:
arr1 - arr2

array([ 12,  54, -53, -33,  11,  54,   1,  55, -35])

In [96]:
arr1 % arr2

array([ 1,  9, 45, 23, 11,  6,  1,  9, 10])

In [97]:
arr1 * arr2

array([ 253, 4455, 4410, 1288, 2520, 1872, 8010, 1794,  450])

In [99]:
gl = np.array([1,3,4,5])

In [100]:
gl

array([1, 3, 4, 5])

In [101]:
np.append(gl,100)

array([  1,   3,   4,   5, 100])

In [102]:
gl

array([1, 3, 4, 5])

In [103]:
gl = np.append(gl,100)

In [104]:
gl

array([  1,   3,   4,   5, 100])

### Zeros

In [105]:
arr = np.zeros([3,2]) # 3 rows and 2 columns

In [106]:
arr

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [107]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [108]:
np.ones([5])

array([1., 1., 1., 1., 1.])

In [109]:
np.ones([3,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [110]:
np.ones([4,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Generate Random Array 

In [111]:
from numpy import ones

In [112]:
from numpy import array

In [113]:
array([10,22,33])

array([10, 22, 33])

In [114]:
arr = np.random.random((3,2))

In [115]:
arr

array([[0.79244363, 0.00387531],
       [0.82930515, 0.31221934],
       [0.89223731, 0.53728243]])

In [116]:
np.random.randn(4,2)

array([[ 0.05956581, -0.25721207],
       [ 0.62469998, -0.19424854],
       [-0.40849209,  0.77359981],
       [ 1.2654957 ,  0.02145312]])

In [128]:
arr = np.array([[11,22,33],[44,55,66],[13,45,78]])

In [306]:
np.array([1,2,3,4], ndmin= 20)

array([[[[[[[[[[[[[[[[[[[[1, 2, 3, 4]]]]]]]]]]]]]]]]]]]])

In [129]:
arr

array([[11, 22, 33],
       [44, 55, 66],
       [13, 45, 78]])

In [130]:
# number of axis or number of dimension

In [131]:
arr.ndim

2

In [132]:
arr.itemsize # each element occupied 4 bytes

4

In [133]:
arr.dtype

dtype('int32')

In [134]:
arr.size

9

In [135]:
arr.shape

(3, 3)

In [171]:
arr = np.array([[11,22,33],[44,55,66],[13,45,78]], dtype = 'int32')

In [172]:
arr

array([[11, 22, 33],
       [44, 55, 66],
       [13, 45, 78]])

In [173]:
arr.dtype

dtype('int32')

In [174]:
arr.size

9

In [175]:
arr.itemsize

4

### Reshape Function

In [184]:
arr = np.arange(32).reshape(2,4,4)

In [185]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]]])

In [198]:
arr = np.arange(128).reshape(4,2,16)

In [199]:
arr

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,
          12,  13,  14,  15],
        [ 16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
          28,  29,  30,  31]],

       [[ 32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
          44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,
          60,  61,  62,  63]],

       [[ 64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
          76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
          92,  93,  94,  95]],

       [[ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107,
         108, 109, 110, 111],
        [112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123,
         124, 125, 126, 127]]])

### Indexing Array

In [200]:
arr = np.random.randint(10,50,10)

In [201]:
arr

array([12, 35, 16, 26, 34, 10, 30, 12, 18, 20])

In [202]:
arr[0]

12

In [203]:
arr[-2]

18

In [213]:
arr = np.random.randint(1,100,32).reshape(4,8)

In [214]:
arr

array([[54, 18, 55, 92, 81, 25,  6, 90],
       [94, 63, 85, 17, 43, 48, 89, 24],
       [32, 87, 20, 88, 24, 32,  8, 58],
       [11, 92,  6, 62, 60, 85,  9, 90]])

In [215]:
arr[0]

array([54, 18, 55, 92, 81, 25,  6, 90])

In [216]:
arr[-1]

array([11, 92,  6, 62, 60, 85,  9, 90])

In [217]:
arr[0][::-1]

array([90,  6, 25, 81, 92, 55, 18, 54])

In [220]:
arr[:2][-1][::-1]

array([24, 89, 48, 43, 17, 85, 63, 94])

In [221]:
arr

array([[54, 18, 55, 92, 81, 25,  6, 90],
       [94, 63, 85, 17, 43, 48, 89, 24],
       [32, 87, 20, 88, 24, 32,  8, 58],
       [11, 92,  6, 62, 60, 85,  9, 90]])

In [222]:
arr[0]

array([54, 18, 55, 92, 81, 25,  6, 90])

In [223]:
arr[1]

array([94, 63, 85, 17, 43, 48, 89, 24])

In [225]:
arr[-1][-3:]

array([85,  9, 90])

In [227]:
arr1 = np.array([[2,4],[4,6]])
arr2 = np.array([[2,6],[3,8]])

In [228]:
arr1

array([[2, 4],
       [4, 6]])

In [229]:
arr2

array([[2, 6],
       [3, 8]])

In [230]:
arr1 + arr2

array([[ 4, 10],
       [ 7, 14]])

In [231]:
arr1

array([[2, 4],
       [4, 6]])

In [232]:
arr2

array([[2, 6],
       [3, 8]])

In [233]:
arr1 @ arr2

array([[16, 44],
       [26, 72]])

In [234]:
a1 = np.array([[4,2],[3,5]])
a2 = np.array([[3,7],[4,2]])

In [235]:
a1 @ a2

array([[20, 32],
       [29, 31]])

In [236]:
np.dot(a1,a2)

array([[20, 32],
       [29, 31]])

In [238]:
np.matmul(a1,a2)

array([[20, 32],
       [29, 31]])

In [239]:
number = np.random.randint(1,100,20)

In [241]:
number

array([64, 50, 16, 33, 72, 15, 26, 52,  5, 39, 45, 35, 35, 93, 85, 46, 65,
       70, 54, 85])

In [242]:
sum(number)

985

In [243]:
number.sum()

985

In [244]:
number.min()

5

In [245]:
number.max()

93

In [246]:
number.std()

23.9747262758097

In [247]:
number.mean()

49.25

In [249]:
np.power(number,2)

array([4096, 2500,  256, 1089, 5184,  225,  676, 2704,   25, 1521, 2025,
       1225, 1225, 8649, 7225, 2116, 4225, 4900, 2916, 7225], dtype=int32)

In [250]:
arr = np.random.randint(1,10,(2,3))

In [251]:
arr

array([[1, 5, 9],
       [3, 2, 5]])

In [252]:
arr.sum(axis = 0)

array([ 4,  7, 14])

In [253]:
arr.sum(axis=1)

array([15, 10])

In [254]:
arr.min(axis = 0)

array([1, 2, 5])

In [255]:
arr.min(axis = 1)

array([1, 2])

### Concatenation of an array

In [257]:
arr1 = np.array([5,7,9])
arr2 = np.array([3,4,7])

In [258]:
arr1 + arr2

array([ 8, 11, 16])

In [259]:
np.concatenate([arr1,arr2])

array([5, 7, 9, 3, 4, 7])

In [263]:
np.concatenate([arr1,arr2], axis=None)

array([5, 7, 9, 3, 4, 7])

In [264]:
arr1 = np.array([[5,7,9],[3,4,7]])
arr2 = np.array([[2,4,6],[2,5,8]])

In [266]:
np.concatenate([arr1,arr2],axis=0)

array([[5, 7, 9],
       [3, 4, 7],
       [2, 4, 6],
       [2, 5, 8]])

In [267]:
# flatten array
np.concatenate([arr1,arr2],axis=None) # by default axis = 0, axis = None (flatten array)
# axis = 1

array([5, 7, 9, 3, 4, 7, 2, 4, 6, 2, 5, 8])

In [269]:
arr1

array([[5, 7, 9],
       [3, 4, 7]])

In [270]:
arr2

array([[2, 4, 6],
       [2, 5, 8]])

In [268]:
np.concatenate([arr1,arr2],axis=1)

array([[5, 7, 9, 2, 4, 6],
       [3, 4, 7, 2, 5, 8]])

### Solution of NumPy

Perform these matrices by your own and analyze the result.

In [271]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[2,5,9],[3,4,5]])

In [272]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [273]:
arr2

array([[2, 5, 9],
       [3, 4, 5]])

In [279]:
np.stack((arr1,arr2), axis = 1)

array([[[1, 2, 3],
        [2, 5, 9]],

       [[4, 5, 6],
        [3, 4, 5]]])

In [277]:
np.hstack((arr1,arr2))

array([[1, 2, 3, 2, 5, 9],
       [4, 5, 6, 3, 4, 5]])

In [280]:
np.vstack((arr1,arr2))

array([[1, 2, 3],
       [4, 5, 6],
       [2, 5, 9],
       [3, 4, 5]])

In [281]:
np.dstack?

In [282]:
a = np.array((1,2,3))
b = np.array((2,3,4))

In [283]:
np.dstack((a,b))

array([[[1, 2],
        [2, 3],
        [3, 4]]])

In [284]:
a = np.array((1,2,3,4))
b = np.array((2,3,4,4))

In [285]:
np.dstack((a,b))

array([[[1, 2],
        [2, 3],
        [3, 4],
        [4, 4]]])

In [286]:
a = np.array((1,2,3,4,6))
b = np.array((2,3,4,4,9))

In [287]:
np.dstack((a,b))

array([[[1, 2],
        [2, 3],
        [3, 4],
        [4, 4],
        [6, 9]]])

In [288]:
# split function

In [292]:
arr = np.random.randint(1,20,10)

In [293]:
arr

array([ 7,  7, 13, 18,  1, 18,  9, 19, 12, 18])

In [294]:
np.split(arr,2)

[array([ 7,  7, 13, 18,  1]), array([18,  9, 19, 12, 18])]

In [296]:
np.split(arr,[3,4])

[array([ 7,  7, 13]), array([18]), array([ 1, 18,  9, 19, 12, 18])]

In [297]:
arr

array([ 7,  7, 13, 18,  1, 18,  9, 19, 12, 18])

In [298]:
np.split(arr,[4,7])

[array([ 7,  7, 13, 18]), array([ 1, 18,  9]), array([19, 12, 18])]

In [299]:
np.array_split(arr,3)

[array([ 7,  7, 13, 18]), array([ 1, 18,  9]), array([19, 12, 18])]