In [1]:
import numpy as np

In [2]:
np_arr = np.array([[1,2,3],[4,5,6]])

In [3]:
np_arr

array([[1, 2, 3],
       [4, 5, 6]])

### Accessing elements based on logical conditions

In [4]:
np_arr > 2

array([[False, False,  True],
       [ True,  True,  True]])

In [5]:
np_arr[np_arr > 2]

array([3, 4, 5, 6])

In [7]:
np_arr < 5

array([[ True,  True,  True],
       [ True, False, False]])

In [8]:
np_arr[np_arr<5]

array([1, 2, 3, 4])

In [9]:
(np_arr > 2) & (np_arr < 5)

array([[False, False,  True],
       [ True, False, False]])

In [10]:
np_arr[(np_arr > 2) & (np_arr < 5)]

array([3, 4])

In [15]:
num_arr = list(np.random.randint(20,80,20))

In [17]:
print(num_arr)

[48, 63, 30, 53, 47, 79, 46, 38, 42, 50, 27, 76, 54, 45, 30, 77, 74, 32, 27, 57]


In [20]:
i = 0; result = []
for num in num_arr:
    if num > 50:
        i = i + 1
        result.append(num)

In [21]:
print(i)

8


In [22]:
print(result)

[63, 53, 79, 76, 54, 77, 74, 57]


In [23]:
arr = np.array(num_arr)

In [25]:
sum(arr > 50)

8

In [26]:
arr[arr > 50]

array([63, 53, 79, 76, 54, 77, 74, 57])

In [27]:
arr[(arr > 30) & (arr < 40)]

array([38, 32])

In [28]:
len(arr[(arr > 30) & (arr < 40)])

2

In [29]:
arr

array([48, 63, 30, 53, 47, 79, 46, 38, 42, 50, 27, 76, 54, 45, 30, 77, 74,
       32, 27, 57])

In [30]:
arr[arr % 2 == 0]

array([48, 30, 46, 38, 42, 50, 76, 54, 30, 74, 32])

In [31]:
arr[arr % 2 != 0]

array([63, 53, 47, 79, 27, 45, 77, 27, 57])

In [32]:
arr[arr % 5 == 0]

array([30, 50, 45, 30])

In [34]:
print(num_arr)

[48, 63, 30, 53, 47, 79, 46, 38, 42, 50, 27, 76, 54, 45, 30, 77, 74, 32, 27, 57]


### If your number is greater than 75, can you find the index of that number?

### numpy Where

In [37]:
np.where(np.array(num_arr) > 75)

(array([ 5, 11, 15], dtype=int64),)

In [40]:
np.where((np.array(num_arr) > 30) & (np.array(num_arr) < 65))

(array([ 0,  1,  3,  4,  6,  7,  8,  9, 12, 13, 17, 19], dtype=int64),)

In [41]:
arr = np.array(num_arr)

In [42]:
arr

array([48, 63, 30, 53, 47, 79, 46, 38, 42, 50, 27, 76, 54, 45, 30, 77, 74,
       32, 27, 57])

In [45]:
np.where(arr > 70, "Naveen",arr)

array(['48', '63', '30', '53', '47', 'Naveen', '46', '38', '42', '50',
       '27', 'Naveen', '54', '45', '30', 'Naveen', 'Naveen', '32', '27',
       '57'], dtype='<U11')

In [47]:
sum(arr > 70)

4

In [48]:
np.where((arr > 40) & (arr < 70),"A",arr)

array(['A', 'A', '30', 'A', 'A', '79', 'A', '38', 'A', 'A', '27', '76',
       'A', 'A', '30', '77', '74', '32', '27', 'A'], dtype='<U11')

In [49]:
arr

array([48, 63, 30, 53, 47, 79, 46, 38, 42, 50, 27, 76, 54, 45, 30, 77, 74,
       32, 27, 57])

In [50]:
lst = list(arr)

In [52]:
print(lst)

[48, 63, 30, 53, 47, 79, 46, 38, 42, 50, 27, 76, 54, 45, 30, 77, 74, 32, 27, 57]


In [53]:
lst[1:-1]

[63, 30, 53, 47, 79, 46, 38, 42, 50, 27, 76, 54, 45, 30, 77, 74, 32, 27]

In [54]:
a = "Abhisheak"

In [55]:
a[1:-1]

'bhishea'

In [57]:
print(lst)

[48, 63, 30, 53, 47, 79, 46, 38, 42, 50, 27, 76, 54, 45, 30, 77, 74, 32, 27, 57]


In [59]:
arr

array([48, 63, 30, 53, 47, 79, 46, 38, 42, 50, 27, 76, 54, 45, 30, 77, 74,
       32, 27, 57])

In [60]:
np.delete(arr,1)

array([48, 30, 53, 47, 79, 46, 38, 42, 50, 27, 76, 54, 45, 30, 77, 74, 32,
       27, 57])

In [61]:
np.delete(arr,[0,-1])

array([63, 30, 53, 47, 79, 46, 38, 42, 50, 27, 76, 54, 45, 30, 77, 74, 32,
       27])

In [62]:
arr

array([48, 63, 30, 53, 47, 79, 46, 38, 42, 50, 27, 76, 54, 45, 30, 77, 74,
       32, 27, 57])

In [63]:
np.where(arr % 2 == 0) # where function is returning index

(array([ 0,  2,  6,  7,  8,  9, 11, 12, 14, 16, 17], dtype=int64),)

In [64]:
np.delete(arr,np.where(arr % 2 == 0) )

array([63, 53, 47, 79, 27, 45, 77, 27, 57])

### Delete

Based on the index we can delete an item from an array.

### Where
If you are passing the condition in where function then this function gives index of an item

In [65]:
arr

array([48, 63, 30, 53, 47, 79, 46, 38, 42, 50, 27, 76, 54, 45, 30, 77, 74,
       32, 27, 57])

In [66]:
np.where(arr % 3 == 0)

(array([ 0,  1,  2,  8, 10, 12, 13, 14, 18, 19], dtype=int64),)

In [67]:
np.delete(arr, np.where(arr % 3 == 0))

array([53, 47, 79, 46, 38, 50, 76, 77, 74, 32])

In [68]:
np.delete(arr, np.where(arr % 3 != 0))

array([48, 63, 30, 42, 27, 54, 45, 30, 27, 57])

In [69]:
np.pi

3.141592653589793

In [70]:
np.e

2.718281828459045

In [71]:
arr = np.array([1,5,np.nan,10,34,np.nan,2])

In [72]:
arr

array([ 1.,  5., nan, 10., 34., nan,  2.])

In [73]:
sum(arr) # nan : not a number

nan

In [74]:
1 * np.nan

nan

In [75]:
1 + np.nan

nan

In [76]:
1 / np.nan

nan

In [77]:
1 -  np.nan

nan

In [78]:
1 % np.nan

nan

In [79]:
arr

array([ 1.,  5., nan, 10., 34., nan,  2.])

In [80]:
np.nansum(arr)

52.0

In [81]:
np.nanmin(arr)

1.0

In [82]:
np.nanmax(arr)

34.0

In [83]:
np.nanmean(arr)

10.4

In [85]:
arr

array([ 1.,  5., nan, 10., 34., nan,  2.])

In [84]:
np.nancumsum(arr)

array([ 1.,  6.,  6., 16., 50., 50., 52.])

In [86]:
np.nanmedian(arr)

5.0

In [87]:
print(dir(np))

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals', '_int_extended_ms

In [88]:
np.__version__

'1.26.4'

### Numpy Playlist:

https://www.youtube.com/playlist?list=PLWuFHho1zKhUGq1be3zUT3Ek5myJrKiIP